### PR TITLE
#162163225 codeclimate test coverage 

### PR DESCRIPTION
**Pull request by joshtrigger**
**what does this PR do?**
sends a test report to codeclimate that shows the test coverage

**Description of tasks to be completed**
after the test pass on CircleCI a test report is to codeclimate that calculates the test coverage of the code

**What are the relevant pivotal tracker stories?**
#162163225

### CODE REVIEW

**Review by SokoPaulSokool — APPROVED** [review]

**Review by kafuuma — APPROVED** [review]
This is ok
Be ready to explain to us during the skill session
Also, squash the commits into one commit

**Comment by bibangamba** [comment]
hi @joshtrigger, don't we need the code climate badges? coverage and maintainability? we're not seeing them in the readme. otherwise, this is good stuff

**Comment by joshtrigger** [comment]
@bibangamba the badges are in the @Kasulejoseph's PR.
@kafuuma willl do

**Comment by Kasulejoseph** [comment]
my PR only has 

> @bibangamba the badges are in the @Kasulejoseph's PR.
> @kafuuma willl do

My PR only has codeclimate badge, please add the maintainability badge in your branch

**Comment by joshtrigger** [comment]
@Kasulejoseph i have added the maintainability badge

**Review by bibangamba — APPROVED** [review]

**Review by Nta1e — APPROVED** [review]

**Review by JaymesKat — CHANGES_REQUESTED** [review]
@joshtrigger You have setup circleci, this is outside the scope of the task since @Kasulejoseph is implementing this with travis. Could you resolve this to pull the coverage from the Travis build instead?

**Review by JaymesKat — APPROVED** [review]
LGTM

**Pull request merged**
