### PR TITLE
 #162163238 Users should be able to follow/unfollow each other

### PR DESCRIPTION
**Pull request by Nta1e**
#### What does this PR do?
Enables users to follow each other
#### Description of tasks to be completed?
- Authenticated users should be able to follow an author on reviewing the author's article
- Authenticated users should be able to see a count of other users who follow them and those they follow
- Authenticated users should be able to see a list of authors they follow and those who follow them
 
#### How can this be manually tested?
- I am currently still working on seeing the list of users who follow the user and those the user follows 
#### What are the relevant pivotal tracker stories?

[ #162163238](https://www.pivotaltracker.com/story/show/162163238)
> An Author can follow other authors
screenshot 2019-01-25 at 11 54 14
> An Author Cannot Follow himself
screenshot 2019-01-25 at 11 51 23

### CODE REVIEW

**Comment by JaymesKat** [comment]
@Nta1e Fix linting errors in .scss files

**Review by bibangamba — CHANGES_REQUESTED** [review]
Please add functionality that asks the user to login if they are not logged in. The components and logic for this were already added in @KicaRonaldOkello's PR (which was merged) so it should be easy to incorporate. Otherwise, the feature works as expected. Good stuff.

**Comment by Nta1e** [comment]
@bibangamba I am going to implement that

**Comment by bibangamba** [comment]
Or you could just hide the follow button when the user is not logged in.

**Comment by Nta1e** [comment]
@bibangamba , I have implemented your feedback. Now when you are not logged in and you try to follow a user, You are asked to login!

**Review by SokoPaulSokool — APPROVED** [review]

**Review by bibangamba — APPROVED** [review]
Great work!!

**Review by joshtrigger — APPROVED** [review]

**Review by JaymesKat — APPROVED** [review]
@Nta1e LGTM

**Pull request merged**
