### PR TITLE
#163015093 add heroku configurations

### PR DESCRIPTION
**Pull request by SokoPaulSokool**
### What does this PR do?
Adds Heroku configurations to enable app deployment to Heroku

### Description of Task to be completed?
Make sure that staging apps are created on Heroku when a pull request is raised.
Enable use the Review apps for testing features implemented in the PR instead of first cloning the repository.

#### How should this be manually tested?
Currently, you can go to [here](https://dashboard.heroku.com/pipelines/8feadd50-2084-4fc5-8bff-64b0350365ac) to view the pipeline.
On the drop-down of the staging app, click deploy a branch. It will be reflected in the pull request of that branch
This branch has app.json. Configurations in that file once put in the default branch, enable Heroku automatically create  Review apps  when PRs are raised

#### Screenshots
screen shot 2019-01-09 at 23 48 09

### What are the relevant pivotal tracker stories?
#163015093

### CODE REVIEW

**Review by joshtrigger — APPROVED** [review]
nice work though it looks like there's a build that failed

**Review by KicaRonaldOkello — APPROVED** [review]

**Review by JaymesKat — CHANGES_REQUESTED** [review]
@SokoPaulSokool Well done. Is there a link to the deployment?
Update the PR description to show how it can be tested. Also, adjust the section for `Description of Task to be completed`, use imperative rather than past tense. You can move the screenshot under the `Screenshots` section at the end.

**Comment by SokoPaulSokool** [comment]
@JaymesKat I have implemented the changes you requested.

**Review by JaymesKat — APPROVED** [review]
LGTM

**Pull request merged**
