### PR TITLE
#163475925 Add git pre-commit hook with eslint checker

### PR DESCRIPTION
**Pull request by bibangamba**
#### What does this PR do?
This PR enables a pre-commit hook with an eslint check.

#### Description of tasks to be completed?
install & configure husky (a javascript package for writing git hooks)

#### How can this be manually tested?
clone the repo to a local machine, make some changes and try to commit. The hook should run `yarn lint` before it runs the `git commit` command completes.

#### What are the relevant pivotal stories?
#163475925

### CODE REVIEW

**Review by Kasulejoseph — APPROVED** [review]
Looks good

**Comment by JaymesKat** [comment]
@bibangamba Looks good. Could you add the `--fix` flag in the `yarn lint` command to automatically fix the errors?

**Comment by bibangamba** [comment]
`--fix` was just added. thanks

**Review by JaymesKat — APPROVED** [review]
@bibangamba Good to go

**Pull request merged**
