### PR TITLE
#162163237 Users should be able to share articles on social media and via email

### PR DESCRIPTION
**Pull request by bibangamba**
#### What does this PR do?
Enable Author's Haven users to share articles on facebook, twitter, and email.

#### Description of tasks to be completed?
Install a helper package for social sharing on react: `react-share`
Create a functional component to render the 3 sharing buttons
For maintainability and quality code, write unit tests that cover this feature's functionality

#### How can this be manually tested?
Go to the PR review app (attached below), log in and navigate to one article (read more). Click on any of the sharing buttons.
This open a new tab or bring up a pop up in which you are prompted to login (not logged in) OR you are prompted to edit the post you are about to share (tweet or post).

#### What are the relevant pivotal tracker stories?
[#162163237
](https://www.pivotaltracker.com/story/show/162163237)

#### Screenshots
Twitter sharing
image

Facebook sharing
image

### CODE REVIEW

**Comment by SokoPaulSokool** [comment]
Nice work. I would be a good idea to make the share icons remain in one position as the user scrolls through the article.

**Review by joshtrigger — APPROVED** [review]

**Comment by bibangamba** [comment]
Thanks for the feedback Paul, going to try and implement this.

**Review by Nta1e — APPROVED** [review]
As long as you Implement @SokoPaulSokool 's Feedback, it LGTM!

**Review by JaymesKat — APPROVED** [review]
LGTM

**Comment by JaymesKat** [comment]
@bibangamba Correct typo in commit message body

**Comment by bibangamba** [comment]
Hi @JaymesKat, I've changed the commit message body

**Pull request merged**
