### PR TITLE
#162163236 article tags for easy filtering

### PR DESCRIPTION
**Pull request by kafuuma**
#### What does this PR do?
Implements a feature for users to add tags to articles which can be used for filtering of articles

#### Description of Task to be completed?
```
- Users  can add tags to articles
- Users can edit tags when they edit articles
- Users can article using tags 
```
#### How should this be manually tested?
```
- Add tags to articles when creating them
- Edit, remove and add tags from articles
- Click on tags to filter articles
```

#### What are the relevant pivotal tracker stories?
[#162163236](https://www.pivotaltracker.com/story/show/162163236)

##### Add tags
tags1

##### Display tags
tags2

##### Create tags
tags3

### CODE REVIEW

**Comment by Nta1e** [comment]
Could you please squash those 8 commits into one?

**Comment by JaymesKat** [comment]
@kafuuma resolve conflicts

**Comment by JaymesKat** [comment]
@kafuuma On the PR app, I am trying to click on different tags, no articles are being shown.
screen shot 2019-01-28 at 13 38 06

**Review by bibangamba — APPROVED** [review]
please correct these statements in your PR body: `- Users can article using tags` & `- Edit, remove and add tags from articles`

**Review by Kasulejoseph — COMMENTED** [review]
I have tested it on the review app, looks good

**Review by Kasulejoseph — APPROVED** [review]

**Review by JaymesKat — APPROVED** [review]
LGTM @kafuuma

**Review by JaymesKat — CHANGES_REQUESTED** [review]
@kafuuma Clean the commits and squash them into one before I can merge.

**Review by SokoPaulSokool — APPROVED** [review]

**Pull request closed without merging**
