### PR TITLE
#162163236 article tags for easy filtering

### PR DESCRIPTION
**Pull request by kafuuma**
#### What does this PR do?
Implements a feature for users to add tags to articles which can be used for filtering of articles

#### Description of Task to be completed?
```
- Users  can add tags to articles
- Users can edit tags when they edit articles
- Users can article using tags 
```
#### How should this be manually tested?
```
- Add tags to articles when creating them
- Edit, remove and add tags from articles
- Click on tags to filter articles
```

#### What are the relevant pivotal tracker stories?
[#162163236](https://www.pivotaltracker.com/story/show/162163236)

##### Add tags
tags1

##### Display tags
tags2

##### Create tags
tags3

### CODE REVIEW

**Review by KicaRonaldOkello — APPROVED** [review]
I think it is good

**Review by bibangamba — APPROVED** [review]
LGTM

**Review by Nta1e — APPROVED** [review]
This is good work @kafuuma ! 👏🏽

**Review by JaymesKat — APPROVED** [review]
@kafuuma Good work

**Pull request merged**
