### PR TITLE
#162163243 Bookmark articles for reading later

### PR DESCRIPTION
**Pull request by Kasulejoseph**
#### What does this PR do?
Implements bookmarking and un bookmarking of articles 
#### Description of Task to be completed?
Allow users to bookmark articles for reading later
#### How should this be manually tested?
Click on the review app at the bottom of this PR, `login` and view a single article.
At the extreme end of the article, there is an icon that resembles a book click on it to bookmark
that specific article and double click on it to un-bookmark that same article.
To view your bookmarked article click on `bookmarks` in the navigation bar.
Login and bookmark an article.
#### What are the relevant pivotal tracker stories?
- #162163243
#### Screenshots
screen shot 2019-02-01 at 08 37 41

### CODE REVIEW

**Comment by JaymesKat** [comment]
@Kasulejoseph Good work, the feature is working fine except I need to click the bookmark icon twice before it turns to blue. The article component should be re-rendered when clicked the first time.

**Comment by JaymesKat** [comment]
When I try to bookmark an article when logged out, I should be able to login first. Currently, nothing happens.

**Comment by Kasulejoseph** [comment]
> When I try to bookmark an article when logged out, I should be able to login first. Currently, nothing happens.

implemented this feedback

**Review by KicaRonaldOkello — COMMENTED** [review]
I think it is good

**Review by KicaRonaldOkello — APPROVED** [review]

**Review by joshtrigger — APPROVED** [review]

**Review by joshtrigger — CHANGES_REQUESTED** [review]
@Kasulejoseph please resolve the merge conflicts

**Review by bibangamba — APPROVED** [review]
LGTM

**Review by JaymesKat — APPROVED** [review]
LGTM

**Pull request merged**
